### PR TITLE
Fix the reference to rxjs commonJS library

### PR DESCRIPTION
**Pull request by shisho585**
Since angular 10 when you try to build something with dependency of commonJS library, it's warn you that your application can be  larger slower application because of this. (reference : https://blog.angular.io/version-10-of-angular-now-available-78960babd41#16c4).
To fix this, you need to import ECMAScript module instead if possible.
In rxjs package is just a little different as shown in this PR. 
It's fix two issues (#197 #181) .

Also i fixed issue #215 by checking if element is not null.

### CODE REVIEW

**Review by silvl — APPROVED** [review]
The changes will fix #216

**Comment by shisho585** [comment]
You mean #215

**Comment by silvl** [comment]
Yes, correct. I mean #215 

When will this be released?

**Comment by shisho585** [comment]
I don't know.
Soon, i hope.
It's waiting to @piotrdz

**Comment by piotrdz** [comment]
At the moment, I am working on stabilising v2 branch of the slider, targeting Angular 6 and rxjs 6. This is next on the list. I will need to run a few compatibility checks to see which version it will land in.

**Comment by silvl** [comment]
Okay, I have just upgraded my project to Angular 9 and it appears the only issue I am having is reported in bug #215, which this change fixes.  Do you have a timeframe?  Is it possible to merge this into the current branch?

**Comment by piotrdz** [comment]
@silvl It's done now.

Please have some patience when asking for merge, as I have to check compatibility before pushing the button. My usual pre-merge and pre-release testing is using the component in Angular apps for each of supported Angular versions (5+ for v1).

v2 and the re-brand to ngx-slider is also coming by the end of the week at the latest.

**Pull request merged**
